// ================================================
// Blender Color Ramp Python Script (.py) Writer
// Generates a Python script for Blender's scripting console
// that creates materials with color ramp nodes
// ================================================

function buildBlenderPy(data) {
    var lines = [];
    lines.push('"""');
    lines.push('Blender Color Ramp Import Script');
    lines.push('Generated by Gradient Converter');
    lines.push('');
    lines.push('Usage: Open in Blender\'s Text Editor and click "Run Script",');
    lines.push('       or paste into the Python Console.');
    lines.push('Each gradient creates a new material with a ColorRamp node.');
    lines.push('"""');
    lines.push('');
    lines.push('import bpy');
    lines.push('');

    for (var p = 0; p < data.Palettes.length; p++) {
        var palette = data.Palettes[p];
        var safeName = palette.Name.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/"/g, '\\"');
        var v = 'g' + p;

        lines.push('# --- ' + safeName + ' ---');
        lines.push('mat = bpy.data.materials.new(name="' + safeName + '")');
        lines.push('mat.use_nodes = True');
        lines.push('nodes = mat.node_tree.nodes');
        lines.push('ramp = nodes.new(type="ShaderNodeValToRGB")');
        lines.push('ramp.label = "' + safeName + '"');
        lines.push('cr = ramp.color_ramp');
        lines.push('cr.interpolation = "LINEAR"');
        lines.push('');

        // Blender starts with 2 elements at positions 0 and 1.
        // We set those first, then add extras.
        for (var c = 0; c < palette.Colours.length; c++) {
            var col = palette.Colours[c];
            var rgba = '(' + col.Red.toFixed(6) + ', ' + col.Green.toFixed(6) + ', ' +
                       col.Blue.toFixed(6) + ', ' + col.Alpha.toFixed(6) + ')';

            if (c === 0) {
                lines.push('cr.elements[0].position = ' + col.Position.toFixed(6));
                lines.push('cr.elements[0].color = ' + rgba);
            } else if (c === 1) {
                lines.push('cr.elements[1].position = ' + col.Position.toFixed(6));
                lines.push('cr.elements[1].color = ' + rgba);
            } else {
                lines.push('el = cr.elements.new(' + col.Position.toFixed(6) + ')');
                lines.push('el.color = ' + rgba);
            }
        }

        // If only 1 colour stop, we still need to set element[1]
        if (palette.Colours.length === 1) {
            var last = palette.Colours[0];
            var lastRgba = '(' + last.Red.toFixed(6) + ', ' + last.Green.toFixed(6) + ', ' +
                           last.Blue.toFixed(6) + ', ' + last.Alpha.toFixed(6) + ')';
            lines.push('cr.elements[1].position = 1.0');
            lines.push('cr.elements[1].color = ' + lastRgba);
        }

        lines.push('');
    }

    lines.push('print("Gradient Converter: Created ' + data.Palettes.length + ' color ramp material(s)")');
    lines.push('');

    return lines.join('\n');
}

function writeBlenderScript(data) {
    var text = buildBlenderPy(data);
    var blob = new Blob([text], { type: 'text/x-python' });
    saveFile(blob, data.Name + '_blender.py');
}
