// Unreal Engine Gradient Export
// Generates a Python script for Unreal Engine's built-in Python scripting API
// Creates CurveLinearColor assets via unreal.CurveLinearColorFactory

function buildUnrealPy(paletteData) {
    var lines = [];
    lines.push('"""');
    lines.push('Unreal Engine Gradient Import Script');
    lines.push('Generated by Universal Gradient Converter');
    lines.push('');
    lines.push('Usage: Run in Unreal Engine via Edit > Execute Python Script');
    lines.push('       or the Output Log (Python) console.');
    lines.push('Creates CurveLinearColor assets in /Game/Gradients/');
    lines.push('"""');
    lines.push('');
    lines.push('import unreal');
    lines.push('');
    lines.push('asset_tools = unreal.AssetToolsHelpers.get_asset_tools()');
    lines.push('');

    for (var i = 0; i < paletteData.Palettes.length; i++) {
        var palette = paletteData.Palettes[i];
        var colours = palette.Colours;
        if (!colours || colours.length === 0) continue;

        var safeName = palette.Name.replace(/[^a-zA-Z0-9_]/g, '_').replace(/_+/g, '_');
        if (!safeName) safeName = 'Gradient_' + (i + 1);

        lines.push('# --- ' + palette.Name + ' ---');
        lines.push('curve_' + i + ' = asset_tools.create_asset(');
        lines.push('    "' + safeName + '",');
        lines.push('    "/Game/Gradients",');
        lines.push('    unreal.CurveLinearColor,');
        lines.push('    unreal.CurveLinearColorFactory()');
        lines.push(')');
        lines.push('');

        // For each color channel (R, G, B, A), add keys
        var channels = ['R', 'G', 'B', 'A'];
        var channelIdx = [0, 1, 2, 3]; // Float curve index in CurveLinearColor

        for (var ch = 0; ch < 4; ch++) {
            lines.push('# Channel: ' + channels[ch]);
            for (var c = 0; c < colours.length; c++) {
                var pos = colours[c].Position !== undefined ? colours[c].Position : c / Math.max(colours.length - 1, 1);
                var val;
                if (ch === 0) val = colours[c].Red;
                else if (ch === 1) val = colours[c].Green;
                else if (ch === 2) val = colours[c].Blue;
                else val = colours[c].Alpha !== undefined ? colours[c].Alpha : 1.0;

                lines.push('curve_' + i + '.get_curve(' + channelIdx[ch] + ').add_key(' +
                    pos.toFixed(6) + ', ' + val.toFixed(6) + ')');
            }
        }
        lines.push('');
        lines.push('unreal.log("Created gradient: ' + palette.Name.replace(/"/g, '\\"') + '")');
        lines.push('');
    }

    lines.push('unreal.log("Done — ' + paletteData.Palettes.length + ' gradient(s) created in /Game/Gradients/")');
    lines.push('');

    return lines.join('\n');
}

function writeUnrealScript(paletteData) {
    var text = buildUnrealPy(paletteData);
    var blob = new Blob([text], { type: 'text/x-python;charset=utf-8' });
    saveFile(blob, paletteData.Name + '_unreal.py');
}
