// ================================================
// 3ds Max Gradient MaxScript (.ms) Writer
// Generates a MaxScript that creates gradient ramp maps
// ================================================

function buildMaxScript(data) {
    var lines = [];
    lines.push('/*');
    lines.push('  3ds Max Gradient Import Script');
    lines.push('  Generated by Gradient Converter');
    lines.push('');
    lines.push('  Usage: Run via MAXScript > Run Script in 3ds Max.');
    lines.push('  Each gradient creates a Gradient_Ramp texmap in the Material Editor.');
    lines.push('*/');
    lines.push('');

    for (var p = 0; p < data.Palettes.length; p++) {
        var palette = data.Palettes[p];
        var safeName = palette.Name.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
        var v = 'gr' + p;

        lines.push('-- ' + safeName);
        lines.push(v + ' = Gradient_Ramp()');
        lines.push(v + '.name = "' + safeName + '"');
        lines.push('');

        // 3ds Max Gradient_Ramp has flags by default at positions 0 and 1.
        // We need to set/add flags for each colour stop.
        // Flag indices are 1-based in MaxScript.

        for (var c = 0; c < palette.Colours.length; c++) {
            var col = palette.Colours[c];
            var r255 = Math.round(col.Red * 255);
            var g255 = Math.round(col.Green * 255);
            var b255 = Math.round(col.Blue * 255);
            var posPercent = (col.Position * 100).toFixed(2);
            var flagIdx = c + 1;

            if (c < 2) {
                // Modify existing default flags (index 1 and 2)
                lines.push(v + '.Gradient_Ramp.Flag__' + flagIdx + '__Position = ' + posPercent);
                lines.push(v + '.Gradient_Ramp.Flag__' + flagIdx + '__Color = color ' + r255 + ' ' + g255 + ' ' + b255);
            } else {
                // Add new flags via the gradient ramp's flag list
                lines.push(v + '.Gradient_Ramp.addFlag (color ' + r255 + ' ' + g255 + ' ' + b255 + ') ' + posPercent);
            }
        }

        lines.push('');
        // Add to the medit sample slots if possible
        lines.push('if meditMaterials.count >= ' + (p + 1) + ' then (');
        lines.push('    m = StandardMaterial()');
        lines.push('    m.name = "' + safeName + '"');
        lines.push('    m.diffuseMap = ' + v);
        lines.push('    meditMaterials[' + (p + 1) + '] = m');
        lines.push(')');
        lines.push('');
    }

    lines.push('messageBox "Gradient Converter: Created ' + data.Palettes.length + ' gradient(s)" title:"Import Complete"');
    lines.push('');

    return lines.join('\n');
}

function writeMaxScript(data) {
    var text = buildMaxScript(data);
    var blob = new Blob([text], { type: 'text/plain' });
    saveFile(blob, data.Name + '_3dsmax.ms');
}
