// ================================================
// Cinema 4D Gradient Python Script (.py) Writer
// Generates a Python script for Cinema 4D's Script Manager
// that creates materials with gradient shaders
// ================================================

function buildCinema4dPy(data) {
    var lines = [];
    lines.push('"""');
    lines.push('Cinema 4D Gradient Import Script');
    lines.push('Generated by Gradient Converter');
    lines.push('');
    lines.push('Usage: Open in Cinema 4D Script Manager and execute.');
    lines.push('Each gradient creates a new material with a gradient shader.');
    lines.push('"""');
    lines.push('');
    lines.push('import c4d');
    lines.push('from c4d import gui');
    lines.push('');

    for (var p = 0; p < data.Palettes.length; p++) {
        var palette = data.Palettes[p];
        var safeName = palette.Name.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/"/g, '\\"');

        lines.push('# --- ' + safeName + ' ---');
        lines.push('mat_' + p + ' = c4d.BaseMaterial(c4d.Mmaterial)');
        lines.push('mat_' + p + '.SetName("' + safeName + '")');
        lines.push('');
        lines.push('shader_' + p + ' = c4d.BaseShader(c4d.Xgradient)');
        lines.push('grad_' + p + ' = shader_' + p + '[c4d.SLA_GRADIENT_GRADIENT]');
        lines.push('');

        // Remove default knots first, then insert ours
        lines.push('# Clear default knots');
        lines.push('while grad_' + p + '.GetKnotCount() > 0:');
        lines.push('    grad_' + p + '.RemoveKnot(0)');
        lines.push('');

        for (var c = 0; c < palette.Colours.length; c++) {
            var col = palette.Colours[c];
            lines.push('grad_' + p + '.InsertKnot(');
            lines.push('    col=c4d.Vector(' +
                col.Red.toFixed(6) + ', ' +
                col.Green.toFixed(6) + ', ' +
                col.Blue.toFixed(6) + '),');
            lines.push('    brightnes=1.0,');
            lines.push('    pos=' + col.Position.toFixed(6) + ',');
            lines.push('    bias=0.5, index=' + c + ')');
        }

        lines.push('');
        lines.push('shader_' + p + '[c4d.SLA_GRADIENT_GRADIENT] = grad_' + p);
        lines.push('mat_' + p + '.InsertShader(shader_' + p + ')');
        lines.push('mat_' + p + '[c4d.MATERIAL_COLOR_SHADER] = shader_' + p);
        lines.push('doc.InsertMaterial(mat_' + p + ')');
        lines.push('');
    }

    lines.push('c4d.EventAdd()');
    lines.push('gui.MessageDialog("Gradient Converter: Created ' + data.Palettes.length + ' gradient material(s)")');
    lines.push('');

    return lines.join('\n');
}

function writeCinema4dScript(data) {
    var text = buildCinema4dPy(data);
    var blob = new Blob([text], { type: 'text/x-python' });
    saveFile(blob, data.Name + '_cinema4d.py');
}
